[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = []

fs_permissions = [
    {access = "read", path = "./broadcast"},
    {access = "read", path = "./reports"}
]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config